pywren: 
    storage_bucket: <BUCKET_NAME>
    storage_backend: aws_s3
    compute_backend: aws_lambda

aws:
    access_key_id : <ACCESS_KEY_ID>
    secret_access_key : <SECRET_ACCESS_KEY>

aws_lambda:
    #region_name : <REGION_NAME> # Optional, overrides 'compute_backend_region' from 'pywren' entry
    execution_role : <EXECUTION_ROLE_ARN>

aws_s3:
    endpoint : <S3_ENDPOINT_URI>
